application: atlantean-force-90113
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.*
  script: datastore101.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
